export const locations = [
  "Kabul, Afghanistan",
  "Tirana, Albania",
  "Algiers, Algeria",
  "Buenos Aires, Argentina",
  "Sydney, Australia",
  "Vienna, Austria",
  "Baku, Azerbaijan",
  "Dhaka, Bangladesh",
  "Brussels, Belgium",
  "La Paz, Bolivia",
  "São Paulo, Brazil",
  "Sofia, Bulgaria",
  "Phnom Penh, Cambodia",
  "Toronto, Canada",
  "Santiago, Chile",
  "Beijing, China",
  "Bogotá, Colombia",
  "Kinshasa, Congo (DRC)",
  "San José, Costa Rica",
  "Zagreb, Croatia",
  "Havana, Cuba",
  "Prague, Czechia",
  "Copenhagen, Denmark",
  "Cairo, Egypt",
  "San Salvador, El Salvador",
  "Tallinn, Estonia",
  "Addis Ababa, Ethiopia",
  "Helsinki, Finland",
  "Paris, France",
  "Berlin, Germany",
  "Accra, Ghana",
  "Athens, Greece",
  "Guatemala City, Guatemala",
  "Port-au-Prince, Haiti",
  "Tegucigalpa, Honduras",
  "Budapest, Hungary",
  "Reykjavík, Iceland",
  "Mumbai, India",
  "Jakarta, Indonesia",
  "Tehran, Iran",
  "Baghdad, Iraq",
  "Tel Aviv, Israel",
  "Rome, Italy",
  "Kingston, Jamaica",
  "Tokyo, Japan",
  "Amman, Jordan",
  "Nairobi, Kenya",
  "Seoul, South Korea",
  "Kuwait City, Kuwait",
  "Vientiane, Laos",
  "Beirut, Lebanon",
  "Tripoli, Libya",
  "Antananarivo, Madagascar",
  "Kuala Lumpur, Malaysia",
  "Bamako, Mali",
  "Mexico City, Mexico",
  "Ulaanbaatar, Mongolia",
  "Casablanca, Morocco",
  "Maputo, Mozambique",
  "Kathmandu, Nepal",
  "Amsterdam, Netherlands",
  "Wellington, New Zealand",
  "Managua, Nicaragua",
  "Lagos, Nigeria",
  "Oslo, Norway",
  "Muscat, Oman",
  "Karachi, Pakistan",
  "Panama City, Panama",
  "Asunción, Paraguay",
  "Lima, Peru",
  "Manila, Philippines",
  "Warsaw, Poland",
  "Lisbon, Portugal",
  "Doha, Qatar",
  "Bucharest, Romania",
  "Moscow, Russia",
  "Riyadh, Saudi Arabia",
  "Dakar, Senegal",
  "Belgrade, Serbia",
  "Singapore, Singapore",
  "Johannesburg, South Africa",
  "Madrid, Spain",
  "Colombo, Sri Lanka",
  "Stockholm, Sweden",
  "Zurich, Switzerland",
  "Damascus, Syria",
  "Taipei, Taiwan",
  "Dushanbe, Tajikistan",
  "Bangkok, Thailand",
  "Tunis, Tunisia",
  "Istanbul, Türkiye",
  "Kyiv, Ukraine",
  "Dubai, United Arab Emirates",
  "London, United Kingdom",
  "New York, United States",
  "Montevideo, Uruguay",
  "Tashkent, Uzbekistan",
  "Caracas, Venezuela",
  "Hanoi, Vietnam",
  "Lusaka, Zambia",
  "Harare, Zimbabwe",
];